---
title: "Tidy Challenge"
author: "Las Quince Letras"
output: 
  prettydoc::html_pretty:
    theme: architect
    highlight: github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      error = FALSE,
                      comment = NA,
                      fig.align = 'center',
                      fig.cap = NULL)
```

## {.tabset .tabset-fade .tabset-pills}

Bienvenida/o al Tidy Challenge. Este es un ejercicio de diagnóstico para que el 
equipo de análisis tenga una mejor idea de tus fortalezas y áreas de oportunidad. 

Tus resultados no serán compartidos ni divulgados a nadie más que a ti. 
Del mismo modo, al finalizar recibirás feedback de parte del equipo Senior en el cuál
recibirás consejos, funciones útiles para el trabajo diario y comentarios constructivos
sobre tu código. También puede ser tu oportunidad para enseñarnos algún método o 
_hack_ que conozcas y que creas que pueda interesarnos.

Este es un reto 100% personal, haz tu mejor esfuerzo y se lo más creativa/o para 
responder cada pregunta. Puedes utilizar cualquier recurso que desees excepto preguntarle 
a cualquier otro miembro del equipo cómo responder alguna pregunta o utilizar un
software distinto a `R`.
Si crees que una pregunta no proporciona suficiente 
información, haz los supuestos que creas convenientes, coméntalos y responde acorde. 

Por último, si no puedes responder una pregunta usando `R`
puedes platicarnos cómo crees que podrías responderla.

Éxito.

### Instrucciones

+ Leer las bases de datos ubicadas en la carpeta `data/` y responde las
preguntas que se encuentran a continuación.
  + ¿Cuáles son los 10 estados con más colonias de abejas?
  + ¿Cuáles son los 10 estados con mayores pérdidas?
  + ¿Cuál es el estado que ha presentado mayores pérdidas de colonias?
  + ¿Cuál es el estado que ha presentado mayores incrementos de colonias?
  + ¿Cuál es el stressor que ocasiona mayores pérdidas?
  + Usando la clasificación por region que se encuentra en la carpeta `cache/`
  responde ¿Qué región es la más propicia para las colonias de abejas?
  + Hay muchos datos faltantes en la base de datos, ¿Cómo lidiarías con ellos? (Platícanos tu respuesta, el código es totalmente opcional)
  
### BONUS

Si te quedaste con ganas de un reto un poco más grande puedes intentar responder 
las siguientes dos preguntas. Estas requieren un nivel
de `R` más avanzado y responderlas o no es opcional.

+ Usa un modelo estadístico para predecir las pérdidas en Arkansas para el primer
periodo del 2022.
+ Haz un mapa de los EEUU y colorea cada estado con base en las ganacias y pérdidas de colonias que tuvo en el 2021.
  






